"""add requirements hierarchy tables

Revision ID: 8f89596258b8
Revises: 001
Create Date: 2026-05-14 10:46:44.449199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f89596258b8'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('close_reasons',
    sa.Column('item_type', sa.Enum('epic', 'feature', 'story', 'task', name='item_type'), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('done', 'rejected', 'duplicate', 'wont_fix', 'deferred', name='close_reason_enum'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('closed_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_close_reasons_item_id'), 'close_reasons', ['item_id'], unique=False)
    op.create_table('epics',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'done', 'rejected', 'duplicate', 'wont_fix', 'deferred', name='item_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='priority'), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epics_project_id'), 'epics', ['project_id'], unique=False)
    op.create_table('features',
    sa.Column('epic_id', sa.UUID(), nullable=False),
    sa.Column('prefix', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'done', 'rejected', 'duplicate', 'wont_fix', 'deferred', name='item_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='priority'), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['epic_id'], ['epics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_epic_id'), 'features', ['epic_id'], unique=False)
    op.create_table('stories',
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('prefix', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor_ref', sa.String(length=255), nullable=True),
    sa.Column('action_text', sa.Text(), nullable=True),
    sa.Column('goal_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'done', 'rejected', 'duplicate', 'wont_fix', 'deferred', name='item_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='priority'), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_feature_id'), 'stories', ['feature_id'], unique=False)
    op.create_table('acceptance_criteria',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acceptance_criteria_story_id'), 'acceptance_criteria', ['story_id'], unique=False)
    op.create_table('tasks',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('prefix', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'done', 'rejected', 'duplicate', 'wont_fix', 'deferred', name='item_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='priority'), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_story_id'), 'tasks', ['story_id'], unique=False)
    op.drop_constraint(op.f('github_connections_project_id_key'), 'github_connections', type_='unique')
    op.drop_index(op.f('ix_github_connections_project_id'), table_name='github_connections')
    op.create_index(op.f('ix_github_connections_project_id'), 'github_connections', ['project_id'], unique=True)
    op.drop_constraint(op.f('organizations_slug_key'), 'organizations', type_='unique')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_github_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_github_id_key'), 'users', ['github_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=False)
    op.create_unique_constraint(op.f('organizations_slug_key'), 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_github_connections_project_id'), table_name='github_connections')
    op.create_index(op.f('ix_github_connections_project_id'), 'github_connections', ['project_id'], unique=False)
    op.create_unique_constraint(op.f('github_connections_project_id_key'), 'github_connections', ['project_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tasks_story_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_acceptance_criteria_story_id'), table_name='acceptance_criteria')
    op.drop_table('acceptance_criteria')
    op.drop_index(op.f('ix_stories_feature_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_features_epic_id'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_epics_project_id'), table_name='epics')
    op.drop_table('epics')
    op.drop_index(op.f('ix_close_reasons_item_id'), table_name='close_reasons')
    op.drop_table('close_reasons')
    # ### end Alembic commands ###
